### ISSUE TITLE
High ram usage when reading large files

### ISSUE THREAD

**Issue by Izrox-sa** [0xlane/pe-sign#2]
Hello!

I Really liked the project and would like to use it in some sort of scanner that scans multiple files. However, when scanning large files RAM usage spikes high after running Pesign::from_pe_path() in windows.

I would appreciate if there were other ways (I see there is 'from_reader' method, but I don't know if it supports buffered reading) or if this could be fixed as running this in backup server or hypervisor (places where there are large single files in range of 100 GB or more) could cause extreme ram usage just to verify signature.

Appreciate your efforts.

**Comment by 0xlane** [comment]
Hello, thank you for your feedback. The project directly uses the external library [exe-rs](https://github.com/frank2/exe-rs) to parse PE files, which is not optimized for large files. The entire file content is read directly into memory, so reading large files does lead to high memory usage. I will work on an optimized version to address this issue shortly. 

The `from_reader` method is only used to directly parse DER format content, while the `from_certificate_table_buf` method is a wrapper for the `from_reader` method. If you need to parse certificates from a PE file, you will still need to use `from_pe_path`.

**Comment by 0xlane** [comment]
Hi, this issue has been improved in v0.1.9, you can give it a try.

**Comment by Izrox-sa** [comment]
Awesome rapid fix! So much faster as well. Appreciate your help!
